openapi: 3.0.1
security: []
info:
  title: UANATACA LTV EXTENSION API DOCUMENTATION
  description: 
    $ref: ./ltv_extension_gui.md
  version: v1
  x-logo:
    url: https://raw.githubusercontent.com/UANATACA/OTP-REPO/main/img/LTV_Extension_En.png
    altText: LTV extension logo